image ai normal = "sprite/ai/ai_normal.png"
image ai normal neck = "sprite/ai/ai_neck_normal.png"
image ai happy laugh = "sprite/ai/ai_happy_laugh.png"
image ai happy laugh neck = "sprite/ai/ai_neck_happy_laugh.png"
image ai shocked = "sprite/ai/ai_shocked.png"
image ai shocked neck = "sprite/ai/ai_neck_shocked.png"
image ai annoyed = "sprite/ai/ai_annoyed.png"
image ai annoyed neck = "sprite/ai/ai_neck_annoyed.png"
image ai serious = "sprite/ai/ai_serious.png"
image ai serious neck = "sprite/ai/ai_neck_serious.png"
image ai worry = "sprite/ai/ai_worry.png"
image ai worry neck = "sprite/ai/ai_neck_worry.png"
image ai smile = "sprite/ai/ai_smile.png"
image ai smile neck = "sprite/ai/ai_neck_smile.png"
image ai notconfident = "sprite/ai/ai_not_confident.png"
image ai notconfident neck = "sprite/ai/ai_neck_not_confident.png"

image amanda normal = "sprite/amanda/amanda_normal.png"
image amanda smile = "sprite/amanda/amanda_smile.png"
image amanda ho = "sprite/amanda/amanda_ho.png"
image amanda hmph = "sprite/amanda/amanda_hmph.png"
image amanda shout = "sprite/amanda/amanda_shout.png"

image g1 normal = "sprite/guyone/guyone_normal.png"
image g1 shout = "sprite/guyone/guyone_shout.png"
image g1 sob = "sprite/guyone/guyone_sob.png"
image g1 wow = "sprite/guyone/guyone_wow.png"
image g1 surprised = "sprite/guyone/guyone_surprised.png"
image g1 blushed = "sprite/guyone/guyone_blushed.png"

image g2 normal = "sprite/guytwo/guytwo_normal.png"
image g2 fierce = "sprite/guytwo/guytwo_fierce.png"
image g2 oh = "sprite/guytwo/guytwo_oh.png"
image g2 shout = "sprite/guytwo/guytwo_shout.png"
image g2 shy = "sprite/guytwo/guytwo_shy.png"
image g2 smile = "sprite/guytwo/guytwo_smile.png"

image grace normal = "sprite/grace/grace_normal.png"
image grace scared = "sprite/grace/grace_scared.png"
image grace shy = "sprite/grace/grace_shy.png"

image graceai normal = "sprite/grace/grace_normal.png"
image graceai shout = "sprite/grace/grace_shout.png"
image graceai tsk = "sprite/grace/grace_tsk.png"

